apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dnixx-apps
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/yomlinux/Pipeline.git
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

